pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success~=^Rust CI.*
    actions:
      merge:
        method: merge
